return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "stylua",
        "shellcheck",
        "shfmt",
        "eslint_d",
        "json-lsp",
        "lua-language-server",
        "typescript-language-server",
        "angular-language-server",
        "astro-language-server",
        "bash-language-server",
        "clojure-lsp",
        "css-lsp",
        "dot-language-server",
        "elm-format",
        "elm-language-server",
        "chrome-debug-adapter",
        "html-lsp",
        "jsonlint",
        "markdownlint",
        "prisma-language-server",
        "rust-analyzer",
        "sql-formatter",
        "svelte-language-server",
        "tailwindcss-language-server",
        "vue-language-server",
      },
    },
  },
}
